// flow-typed signature: 9881182361ae40dc0681166ae6a3b3d6
// flow-typed version: <<STUB>>/penthouse_v^1.4.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'penthouse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'penthouse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'penthouse/lib/browser-sandbox/pruneNonCriticalCss' {
  declare module.exports: any;
}

declare module 'penthouse/lib/browser-sandbox/pruneNonCriticalSelectors' {
  declare module.exports: any;
}

declare module 'penthouse/lib/browser-sandbox/replacePageCss' {
  declare module.exports: any;
}

declare module 'penthouse/lib/core' {
  declare module.exports: any;
}

declare module 'penthouse/lib/index' {
  declare module.exports: any;
}

declare module 'penthouse/lib/non-matching-media-query-remover' {
  declare module.exports: any;
}

declare module 'penthouse/lib/normalize-css-module' {
  declare module.exports: any;
}

declare module 'penthouse/lib/normalize-css' {
  declare module.exports: any;
}

declare module 'penthouse/lib/phantomjs/normalize-css' {
  declare module.exports: any;
}

declare module 'penthouse/lib/postformatting/comment-remover' {
  declare module.exports: any;
}

declare module 'penthouse/lib/postformatting/embedded-base64-remover' {
  declare module.exports: any;
}

declare module 'penthouse/lib/postformatting/final-rule-remover' {
  declare module.exports: any;
}

declare module 'penthouse/lib/postformatting/index' {
  declare module.exports: any;
}

declare module 'penthouse/lib/postformatting/rule-selector-remover' {
  declare module.exports: any;
}

declare module 'penthouse/lib/postformatting/unused-fontface-remover' {
  declare module.exports: any;
}

declare module 'penthouse/lib/postformatting/unused-keyframe-remover' {
  declare module.exports: any;
}

declare module 'penthouse/lib/postformatting/unwanted-properties-remover' {
  declare module.exports: any;
}

declare module 'penthouse/lib/selectors-profile' {
  declare module.exports: any;
}

declare module 'penthouse/lib/src/browser-sandbox/replacePageCss' {
  declare module.exports: any;
}

declare module 'penthouse/lib/util/chromeProcessesRunning' {
  declare module.exports: any;
}

// Filename aliases
declare module 'penthouse/lib/browser-sandbox/pruneNonCriticalCss.js' {
  declare module.exports: $Exports<'penthouse/lib/browser-sandbox/pruneNonCriticalCss'>;
}
declare module 'penthouse/lib/browser-sandbox/pruneNonCriticalSelectors.js' {
  declare module.exports: $Exports<'penthouse/lib/browser-sandbox/pruneNonCriticalSelectors'>;
}
declare module 'penthouse/lib/browser-sandbox/replacePageCss.js' {
  declare module.exports: $Exports<'penthouse/lib/browser-sandbox/replacePageCss'>;
}
declare module 'penthouse/lib/core.js' {
  declare module.exports: $Exports<'penthouse/lib/core'>;
}
declare module 'penthouse/lib/index.js' {
  declare module.exports: $Exports<'penthouse/lib/index'>;
}
declare module 'penthouse/lib/non-matching-media-query-remover.js' {
  declare module.exports: $Exports<'penthouse/lib/non-matching-media-query-remover'>;
}
declare module 'penthouse/lib/normalize-css-module.js' {
  declare module.exports: $Exports<'penthouse/lib/normalize-css-module'>;
}
declare module 'penthouse/lib/normalize-css.js' {
  declare module.exports: $Exports<'penthouse/lib/normalize-css'>;
}
declare module 'penthouse/lib/phantomjs/normalize-css.js' {
  declare module.exports: $Exports<'penthouse/lib/phantomjs/normalize-css'>;
}
declare module 'penthouse/lib/postformatting/comment-remover.js' {
  declare module.exports: $Exports<'penthouse/lib/postformatting/comment-remover'>;
}
declare module 'penthouse/lib/postformatting/embedded-base64-remover.js' {
  declare module.exports: $Exports<'penthouse/lib/postformatting/embedded-base64-remover'>;
}
declare module 'penthouse/lib/postformatting/final-rule-remover.js' {
  declare module.exports: $Exports<'penthouse/lib/postformatting/final-rule-remover'>;
}
declare module 'penthouse/lib/postformatting/index.js' {
  declare module.exports: $Exports<'penthouse/lib/postformatting/index'>;
}
declare module 'penthouse/lib/postformatting/rule-selector-remover.js' {
  declare module.exports: $Exports<'penthouse/lib/postformatting/rule-selector-remover'>;
}
declare module 'penthouse/lib/postformatting/unused-fontface-remover.js' {
  declare module.exports: $Exports<'penthouse/lib/postformatting/unused-fontface-remover'>;
}
declare module 'penthouse/lib/postformatting/unused-keyframe-remover.js' {
  declare module.exports: $Exports<'penthouse/lib/postformatting/unused-keyframe-remover'>;
}
declare module 'penthouse/lib/postformatting/unwanted-properties-remover.js' {
  declare module.exports: $Exports<'penthouse/lib/postformatting/unwanted-properties-remover'>;
}
declare module 'penthouse/lib/selectors-profile.js' {
  declare module.exports: $Exports<'penthouse/lib/selectors-profile'>;
}
declare module 'penthouse/lib/src/browser-sandbox/replacePageCss.js' {
  declare module.exports: $Exports<'penthouse/lib/src/browser-sandbox/replacePageCss'>;
}
declare module 'penthouse/lib/util/chromeProcessesRunning.js' {
  declare module.exports: $Exports<'penthouse/lib/util/chromeProcessesRunning'>;
}
